image: node:12.16.1

pipelines:
  custom:
    deployment-to-staging:
      - step:
          deployment: staging
          script:
            - export METEOR_ALLOW_SUPERUSER=true
            - export DISABLE_CLIENT_STATS=true
            - curl https://install.meteor.com/ | sh
            - npm install --omit=dev
            - meteor build ./build --architecture os.linux.x86_64
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: 'ualettdev'
                SERVER: $REMOTE_HOST
                REMOTE_PATH: '/home/ualettdev/backend/build.tar.gz'
                LOCAL_PATH: './build/build.tar.gz'
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'ualettdev'
                SERVER: $REMOTE_HOST
                COMMAND: 'tar -xzf /home/ualettdev/backend/build.tar.gz -C /home/ualettdev/backend && cd /home/ualettdev/backend/bundle/programs/server && npm install --omit=dev'
