import admin from 'firebase-admin';
import {
  FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X_509_CERT_URL,
  FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_X_509_CERT_URL,
  FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
  FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
  FIREBASE_SERVICE_ACCOUNT_PROJECT_ID,
  FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
  FIREBASE_SERVICE_ACCOUNT_TYPE
} from '../keys';

admin.initializeApp({
  credential: admin.credential.cert({
    type: FIREBASE_SERVICE_ACCOUNT_TYPE,
    project_id: FIREBASE_SERVICE_ACCOUNT_PROJECT_ID,
    private_key_id: FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
    private_key: FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
    client_email: FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
    client_id: FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
    auth_uri: FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
    token_uri: FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
    auth_provider_x509_cert_url: FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X_509_CERT_URL,
    client_x509_cert_url: FIREBASE_SERVICE_ACCOUNT_CLIENT_X_509_CERT_URL
  }),
  databaseURL: 'https://ualett-266c9.firebaseio.com'
});

export default admin;
