/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/restrict-template-expressions */
import { config } from 'dotenv';

config({ path: `${process.env.PWD}/.env` });

export const {
  ENV,
  RUN_CRON_JOBS,
  SENTRY,

  MAIL_FROM,
  MAIL_SMTP,

  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_DOCS_BUCKET_NAME,
  AWS_SIGNATURES_BUCKET_NAME,
  AWS_BUCKET_NAME,
  AWS_DL_BUCKET_NAME,

  TRUSTPILOT_AUTOMATIC_INVITE_BCC,

  SMSPROVIDER,

  TWILIO_FROM,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_VERIFY_SERVICE_ID,
  TWILIO_MESSAGING_MARKETING_SID,
  TWILIO_MESSAGING_ACCOUNT_NOTIFICATION_SID,
  TWILIO_MESSAGING_CUSTOMER_CARE_SID,

  PLIVIO_FROM,
  PLIVIO_AUTH_ID,
  PLIVIO_AUTH_TOKEN,

  TWILIO_CONTACT_CENTER_ACCOUNT_SID,
  TWILIO_CONTACT_CENTER_AUTH_TOKEN,
  TWILIO_CONTACT_CENTER_WORKSPACE,

  ONESIGNAL_REST_API_KEY,
  ONESIGNAL_REST_URL,
  ONESIGNAL_APP_ID,
  ONESIGNAL_URL,

  PLAID_CLIENT_ID,
  PLAID_SECRET,
  PLAID_PUBLIC_KEY,
  PLAID_ENVIRONMENT,
  PLAID_PRODUCT,
  PLAID_IDV_TEMPLATE_ID,
  PLAID_WEBHOOK_URL,

  DWOLLA_KEY,
  DWOLLA_SECRET,
  DWOLLA_ENVIRONMENT,
  DWOLLA_WEBHOOK_SECRET,
  DWOLLA_FUNDING_SOURCES,
  DWOLLA_BANK_FUNDING_SOURCES,
  DWOLLA_BANK_FUNDING_SOURCE_NAME,
  DWOLLA_ACCOUNT,

  BITRIX24_SECRETS,
  BITRIX24_API_SECRET,

  SQREEN_TOKEN,

  SUPPORT_NUMBER,

  EXPORT_METHOD_SECRET,

  API_SECRETS_GET_INVITED,
  API_SECRETS_TELEGRAM_BOT,
  API_SECRETS_GET_INFO,
  API_SECRETS_DATA_TAPE,
  API_SECRETS_BO_CLIENT_GET_FILE,
  API_SECRETS_GET_USER_DOCUMENT,

  IP_ACCESS_WHITELIST,
  API_IP_WHITELIST,

  SERVICES_AGREEMENT_PROCESSOR,
  SERVICES_PROMOTERS_APP,

  BOTS_WEBHOOKS_DWOLLA_BOT,
  BOTS_WEBHOOKS_BO_BOT,

  FIREBASE_SERVICE_ACCOUNT_TYPE,
  FIREBASE_SERVICE_ACCOUNT_PROJECT_ID,
  FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
  FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
  FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
  FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
  FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X_509_CERT_URL,
  FIREBASE_SERVICE_ACCOUNT_CLIENT_X_509_CERT_URL,

  WEBNOTIFICATIONS_PUBLIC_KEY,
  WEBNOTIFICATIONS_PRIVATE_KEY,

  JIRA_BASE_URL,
  JIRA_API_KEY,
  JIRA_PROJECT_KEY,
  JIRA_EMAIL_AUTH,
  JIRA_OVERDUE,

  ARGYLE_URL,
  ARGYLE_API_KEY,
  ARGYLE_API_SECRET,
  ARGYLE_WEBHOOK_SECRET,

  S3_REGION,
  S3_BUCKET_NAME,
  S3_DOCSBUCKETNAME,
  S3_ACCESS_KEY,
  S3_ACCESS_KEY_ID,

  TRUSTPILOT_API_KEY,
  TRUSTPILOT_SECRET
} = process.env;
